### ISSUE TITLE
Property language of the Dictionary is always undefined

### ISSUE THREAD

**Issue by lastuvka** [seznam/IMA.js-core#166]
MessageFormatDictionary´s Init method is expecting  [config.language](https://github.com/seznam/IMA.js-core/blob/master/dictionary/MessageFormatDictionary.js#L65)
but in the argument is [config.$Language](https://github.com/seznam/IMA.js-core/blob/master/main.js#L63) so that in this case the language is never set. 

Possible workaround is to add these lines to app/config/service.js:
```
let dictionaryConfig = config.dictionary;
dictionaryConfig.language = dictionaryConfig.$Language;
oc.get('$Dictionary').init(dictionaryConfig);
```

**Comment by mjancarik** [comment]
fixed in [ima@0.16.9](https://www.npmjs.com/package/ima/v/0.16.9)
