### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by mjancarik** [seznam/IMA.js-core#2]
Implement custom events through DOM and add listener on window, which call controller method.

**Comment by xurban42** [comment]
https://github.com/seznam/IMA.js-core/tree/i2-custom-events

**Comment by xurban42** [comment]
Checklist:
- [x] Implement EventBus
- [x] Integrate it into PageManager for use with active controller
- [x] Tests
- [ ] Code review with refactoring.
- [ ] Update examples - use custom events instead dispatcher.

**Comment by xurban42** [comment]
https://github.com/seznam/IMA.js-core/commit/8fe82673b5e53368953799d9c43d83190d0f97ca

And merged to next.
