### ISSUE TITLE
Documentation build fix

### ISSUE THREAD

**Issue by xurban42** [seznam/IMA.js-core#46]
We have to solve YUIDoc interpretation problems of objects with a known set of properties:

```
/**
 * @param {{a: number, b: string, c}} myObj description
 */
```

YUIdoc doesn't know this syntax.

We should replace it with this:

```
/**
 * @param {Object} myObj description
 * @param {number} myObj.a description
 * @param {string} myObj.b description
 * @param {} myObj.c description
 */
```

What do you thing?

**Comment by jurca** [comment]
I'll write a preprocessor to translate it to YUIDoc syntax, since we would have to revert these modifications after switching to JSDoc.

**Comment by jurca** [comment]
Looks like a switch to JSDoc might happen "soon" . JSDoc is already in 3.4.0-dev version (https://github.com/jsdoc3/jsdoc/blob/master/package.json), the 3.4.0 supports ES6 syntax (I wonder if the React JSX syntax will have a negative effect).

See: https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-124713014

**Comment by mjancarik** [comment]
Who do you fix it?

**Comment by mjancarik** [comment]
We use JSDoc now.
