### ISSUE TITLE
Http requests - Clearing cache after POST

### ISSUE THREAD

**Issue by xurban42** [seznam/IMA.js-core#6]
If you have enabled caching of http request responses (on GET). And then you will make POST to the same url. After second GET you will get cached data.

Discuss if cleaning cache for this urls should be in IMA.js-core or try to find other solution.

**Comment by jurca** [comment]
The cache should be completely cleared after any non-GET request, due to various embeds in the REST API responses

**Comment by ondras** [comment]
> The cache should be completely cleared after any non-GET request, due to various embeds in the REST API responses

After **any non-idemponent / non-safe** HTTP method: http://restcookbook.com/HTTP%20Methods/idempotency/
