### ISSUE TITLE
Sending file throw the IMA.js proxy (using $Http)

### ISSUE THREAD

**Issue by michalonderko** [seznam/IMA.js-core#71]

**Comment by jurca** [comment]
Fixed in https://github.com/seznam/IMA.js-server/commit/5bcc908a3e86d3b94fc2d722718e4465315034d8

**Comment by jurca** [comment]
Related commit: https://github.com/seznam/IMA.js-skeleton/commit/48791537eb964d7e386f42a4d2769133c3d699b3
