### ISSUE TITLE
Self-XSS

### ISSUE THREAD

**Issue by onovy** [seznam/IMA.js-core#84]
https://en.wikipedia.org/wiki/Self-XSS

Facebook, Google and others are trying to mitigate Self-XSS security attack by sending simple message into console:

Facebook (in cz):
Zadržte!
Tato funkce prohlížeče je určena pro vývojáře. Pokud vám někdo řekl, ať sem něco zkopírujete, abyste tím aktivovali nějakou funkci Facebooku nebo hackovali něčí účet, pak byste měli vědět, že jde o podvod a že danému člověku poskytnete přístup ke svému Facebook účtu.
Další informace najdete na https://www.facebook.com/selfxss

IMA.js should/could do same think.

**Comment by mjancarik** [comment]
We created [ima-plugin-self-xss](https://github.com/seznam/IMA.js-plugin-self-xss) for this purpose.
