### ISSUE TITLE
Method this.link() in Views not working as expected

### ISSUE THREAD

**Issue by ivo-urbanek** [seznam/IMA.js-core#91]
Let have route named 'search': `/hledej/:?phrase/:?categorySeo/:?locality/:?price/:?sort/:?strana`

Now in any view we will use `this.link()`:
```  
      console.log('link testA=', this.link('search', {phrase: "spojka", categorySeo: ""}))
      console.log('link testB=', this.link('search', {categorySeo: "", phrase: "spojka"}))
```
 
Results:
 
link testA= http://local.inzeraty.test/hledej/spojka  (it's OK)
link testB= http://local.inzeraty.test/hledej?phrase=spojka

The order of parameters cannot affect result of 'link' method

**Comment by mjancarik** [comment]
It's bug in https://github.com/seznam/IMA.js-core/blob/master/router/Route.js. 

I think it could be in https://github.com/seznam/IMA.js-core/blob/master/router/Route.js#L344:
```
paramValue ? '$1' + encodeURIComponent(paramValue) +  '$2' : '$2'
```

But I am not sure so write unit test for that and try to fix it.

**Comment by mjancarik** [comment]
Merged https://github.com/seznam/IMA.js-core/pull/92
